// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEj65a5TeKubmAmVXlOP7YUwixACuS90',
    appId: '1:521279787398:web:5a2959d4c43cc032485c07',
    messagingSenderId: '521279787398',
    projectId: 'barbershop-flutter-41f45',
    authDomain: 'barbershop-flutter-41f45.firebaseapp.com',
    storageBucket: 'barbershop-flutter-41f45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_n48oKJtEpAc_eKBIJdxqvhbvK8iSiVw',
    appId: '1:521279787398:android:a18cd8c33749b97a485c07',
    messagingSenderId: '521279787398',
    projectId: 'barbershop-flutter-41f45',
    storageBucket: 'barbershop-flutter-41f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zY9FZEouf-4dtn4UYhsSk8mjpsaJgyo',
    appId: '1:521279787398:ios:b19347eef49f99ef485c07',
    messagingSenderId: '521279787398',
    projectId: 'barbershop-flutter-41f45',
    storageBucket: 'barbershop-flutter-41f45.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2zY9FZEouf-4dtn4UYhsSk8mjpsaJgyo',
    appId: '1:521279787398:ios:b19347eef49f99ef485c07',
    messagingSenderId: '521279787398',
    projectId: 'barbershop-flutter-41f45',
    storageBucket: 'barbershop-flutter-41f45.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAEj65a5TeKubmAmVXlOP7YUwixACuS90',
    appId: '1:521279787398:web:4bb5b94114606aaf485c07',
    messagingSenderId: '521279787398',
    projectId: 'barbershop-flutter-41f45',
    authDomain: 'barbershop-flutter-41f45.firebaseapp.com',
    storageBucket: 'barbershop-flutter-41f45.firebasestorage.app',
  );
}
